version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3008:3008'
    environment:
      - NODE_ENV=production
      - PORT=3008
      - DATABASE_HOST=notification-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=notification_service_db
      - DATABASE_USER=notification_service_user
      - DATABASE_PASSWORD=notification_service_password
    depends_on:
      - notification-db
    networks:
      - notification-network

  notification-db:
    image: postgres:16-alpine
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_DB=notification_service_db
      - POSTGRES_USER=notification_service_user
      - POSTGRES_PASSWORD=notification_service_password
    volumes:
      - notification-db-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - notification-network

volumes:
  notification-db-data:

networks:
  notification-network:
    driver: bridge
